/********************************************************************/
/*                  SOFTWARE COPYRIGHT NOTICE                        */
/*                             Cardinal                             */
/*                                                                  */
/*                  (c) 2021 UChicago Argonne, LLC                  */
/*                        ALL RIGHTS RESERVED                       */
/*                                                                  */
/*                 Prepared by UChicago Argonne, LLC                */
/*               Under Contract No. DE-AC02-06CH11357               */
/*                With the U. S. Department of Energy               */
/*                                                                  */
/*             Prepared by Battelle Energy Alliance, LLC            */
/*               Under Contract No. DE-AC07-05ID14517               */
/*                With the U. S. Department of Energy               */
/*                                                                  */
/*                 See LICENSE for full restrictions                */
/********************************************************************/

#ifdef ENABLE_OPENMC_COUPLING
#include "StructuredMeshTally.h"

#include "OpenMCCellAverageProblem.h"

registerMooseObject("CardinalApp", StructuredMeshTally);

InputParameters
StructuredMeshTally::validParams()
{
  auto params = TallyBase::validParams();
  params.addClassDescription(
      "A tally which maps results onto an OpenMC structured mesh (regular or rectilinear) "
      "and reads them back into a native libMesh mesh generated by this object.");

  params.addParam<MooseEnum>("mesh_type",
                             MooseEnum("regular rectilinear", "regular"),
                             "Whether to use a regular (uniform) or rectilinear "
                             "(non-uniform) OpenMC mesh.");

  params.addRangeParam<unsigned int>(
      "dimensions", 1, 3, "Number of spatial dimensions of the structured mesh (1, 2, or 3).");

  params.addRequiredParam<std::vector<Real>>("lower_left",
                                             "Lower-left corner coordinates of the mesh.");

  params.addParam<std::vector<Real>>("upper_right",
                                     "Upper-right corner coordinates of the mesh. For a regular "
                                     "mesh, either 'upper_right' or 'width' must be provided.");

  params.addParam<std::vector<Real>>(
      "width", "Uniform width of the mesh cells along each axis. For a regular mesh, "
               "either 'upper_right' or 'width' must be provided.");

  params.addParam<unsigned int>("nx", "Number of cells in the x-direction.");
  params.addParam<unsigned int>("ny", "Number of cells in the y-direction.");
  params.addParam<unsigned int>("nz", "Number of cells in the z-direction.");

  params.addParam<std::vector<Real>>(
      "x_grid", "Sorted x-coordinates of the grid lines for a rectilinear mesh.");
  params.addParam<std::vector<Real>>(
      "y_grid", "Sorted y-coordinates of the grid lines for a rectilinear mesh.");
  params.addParam<std::vector<Real>>(
      "z_grid", "Sorted z-coordinates of the grid lines for a rectilinear mesh.");

  return params;
}

StructuredMeshTally::StructuredMeshTally(const InputParameters & parameters)
  : TallyBase(parameters),
    _dimension(getParam<unsigned int>("dimensions")),
    _mesh_type(getParam<MooseEnum>("mesh_type") == "rectilinear" ? structured_mesh::MeshType::RECTILINEAR
                                                                 : structured_mesh::MeshType::REGULAR)
{
  // Structured meshes are incompatible with the random ray solver; that solver uses
  // tracklength estimators which are not defined for the structured spatial filters treated here.
  if (_openmc_problem.runRandomRay())
    mooseError("Structured mesh tallies are not supported when using the random ray solver!");

  // The structured mesh is fully independent of the [Mesh], so we reuse it as-is.
  _mesh = std::make_unique<structured_mesh::StructuredMesh>(
      buildCoordinates(), _dimension, _mesh_type);
}

std::array<std::vector<Real>, 3>
StructuredMeshTally::buildCoordinates() const
{
  std::array<std::vector<Real>, 3> coords;

  if (_mesh_type == structured_mesh::MeshType::RECTILINEAR)
  {
    // The grid lines fully describe the mesh; cell counts are derived from them.
    const std::vector<std::vector<Real>> grids{getParam<std::vector<Real>>("x_grid"),
                                               getParam<std::vector<Real>>("y_grid"),
                                               getParam<std::vector<Real>>("z_grid")};
    for (unsigned int i = 0; i < 3; ++i)
      if (i < _dimension)
      {
        if (grids[i].size() < 2)
        {
          std::string names[]{"x_grid", "y_grid", "z_grid"};
          paramError(names[i], "Each used grid must be provided with at least two points.");
        }
        coords[i] = grids[i];
      }
      else
        coords[i] = {};
  }
  else
  {
    const auto & lower_left = getParam<std::vector<Real>>("lower_left");
    if (lower_left.size() != _dimension)
      paramError("lower_left",
                 "The 'lower_left' must have a number of entries equal to 'dimensions'.");

    std::vector<Real> upper_right;
    std::vector<unsigned int> n;
    const std::vector<unsigned int> counts = {isParamValid("nx") ? getParam<unsigned int>("nx") : 0,
                                              isParamValid("ny") ? getParam<unsigned int>("ny") : 0,
                                              isParamValid("nz") ? getParam<unsigned int>("nz") : 0};

    if (isParamValid("upper_right"))
      upper_right = getParam<std::vector<Real>>("upper_right");
    else if (isParamValid("width"))
    {
      const auto & width = getParam<std::vector<Real>>("width");
      if (width.size() != _dimension)
        paramError("width", "The 'width' must have a number of entries equal to 'dimensions'.");

      upper_right = lower_left;
      for (unsigned int i = 0; i < _dimension; ++i)
        upper_right[i] = lower_left[i] + counts[i] * width[i];
    }
    else
      paramError("upper_right", "Either 'upper_right' or 'width' must be provided.");

    if (upper_right.size() != _dimension)
      paramError("upper_right",
                 "The 'upper_right' must have a number of entries equal to 'dimensions'.");

    for (unsigned int a = 0; a < _dimension; ++a)
    {
      unsigned int ncells = counts[a];
      if (ncells == 0)
        paramError("nx", "A cell count must be provided for each used axis.");

      coords[a].resize(ncells + 1);
      for (unsigned int j = 0; j <= ncells; ++j)
        coords[a][j] = lower_left[a] + (upper_right[a] - lower_left[a]) * j / ncells;
    }
    for (unsigned int a = _dimension; a < 3; ++a)
      coords[a].clear();
  }

  return coords;
}

std::pair<unsigned int, openmc::Filter *>
StructuredMeshTally::spatialFilter()
{
  // Build the OpenMC structured mesh and the native libMesh mesh.
  _mesh->buildOpenMCMesh();
  _mesh->setID(-1);
  _mesh->buildLibMeshMesh(_openmc_problem.getMooseMesh().getMesh().comm());

  // Create one scalar field per (score, external-filter-bin) combination.
  for (const auto & name : getAuxVarNames())
    _mesh->addScalarField(name);

  _mesh_filter = dynamic_cast<openmc::MeshFilter *>(openmc::Filter::create("mesh"));
  _mesh_filter->set_mesh(_mesh->meshIndex());

  return std::make_pair(openmc::model::tally_filters.size() - 1, _mesh_filter);
}

void
StructuredMeshTally::resetTally()
{
  TallyBase::resetTally();

  // Erase the OpenMC mesh.
  openmc::model::meshes.erase(openmc::model::meshes.begin() + _mesh->meshIndex());
}

Real
StructuredMeshTally::storeResultsInner(const std::vector<unsigned int> & /*var_numbers*/,
                                       unsigned int local_score,
                                       const std::vector<OMCTensor> & tally_vals,
                                       bool norm_by_src_rate)
{
  Real total = 0.0;

  for (unsigned int ext_bin = 0; ext_bin < _num_ext_filter_bins; ++ext_bin)
  {
    std::vector<Real> field_values(_mesh->nBins(), 0.0);

    for (unsigned int e = 0; e < _mesh->nBins(); ++e)
    {
      Real unnormalized_tally = tally_vals[local_score](ext_bin * _mesh->nBins() + e);

      Real volumetric_tally = unnormalized_tally;
      volumetric_tally *=
          norm_by_src_rate
              ? _openmc_problem.tallyMultiplier(_tally_score[local_score],
                                                _local_mean_tally[local_score]) /
                    _mesh->binVolume(e) * _openmc_problem.scaling() *
                    _openmc_problem.scaling() * _openmc_problem.scaling()
              : 1.0;

      total += _ext_bins_to_skip[ext_bin] ? 0.0 : unnormalized_tally;
      field_values[e] = volumetric_tally;
    }

    // Field index matches the (score, ext-bin) ordering of getAuxVarNames().
    unsigned int field = local_score * _num_ext_filter_bins + ext_bin;
    _mesh->setBinValues(field, field_values);
  }

  return total;
}
#endif